import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import StoreProvider from "./StoreProvider";
import {GoogleTagManager} from "@next/third-parties/google"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">  
      <body className={inter.className+' _wide'}>
          <StoreProvider>
            <NavBar/>
                {children}
            <Footer/>
          </StoreProvider>
      </body>
      {/* <GoogleTagManager gtmId="GTM-PBG99HM8"/> */}
    </html>
  );
}
